version: '3.8'

services:
  payment:
    build: . 
    container_name: payment-service 
    ports:
    
      - "3055:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    
      - /app/node_modules
 
    restart: unless-stopped 
